# CI build definition for https://ci.appveyor.com/project/olegsych/simply-random
# To learn more, see http://www.appveyor.com/docs/appveyor-yml

version: 0.1.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

skip_tags: true

image: Visual Studio 2017

install:
- git submodule update --init --recursive

build_script:
- msbuild simply.random.sln /m /p:Platform=x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- msbuild simply.random.sln /m /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
- vstest.console bin\debug\Win32\test.dll /Platform:x86 /logger:Appveyor
- vstest.console bin\debug\x64\test.dll /Platform:x64 /logger:Appveyor /inIsolation

after_test:
- nuget pack "src\simply.random.nuspec" -BasePath "src" -OutputDirectory "bin\debug" -Properties "version=%appveyor_build_version%"

artifacts:
- path: bin\debug\*.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: 236NXQ/p6GSTraxqHTtmNVFcDJlTwDjwxzbdJIcDpk8Lu7hAkz1ThK6eqeVeTMz6
  skip_symbols: true
- provider: GitHub
  auth_token:
    secure: 0odiqbMNXJj+DNBK/pFP5to5mGxy1JfdSpA6dUA233dNgQitI78fjDm5vgmafgpR
  artifact: /.*\.nupkg/

nuget:
  project_feed: true
  disable_publish_on_pr: true
